# Generated by Django 3.2.6 on 2022-01-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tododatamodel',
            name='activity',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='inactive', max_length=10),
        ),
    ]
