# Generated by Django 3.2.6 on 2022-01-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tododatamodel_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododatamodel',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
